### ISSUE TITLE
FR: Read just specified keys

### ISSUE THREAD

**Issue by aensidhe** [Kralizek/AWSSecretsManagerConfigurationExtensions#24] opened 2020-04-04 21:25 UTC
Hi.

Thanks for great library.

We don't allow our applications in production to enumerate secrets in account. Instead we give them one or several full paths to secrets that app will need and it can access only them.

I can provide a PR, but I'm not sure how to approach this. E.g. we can provide something like `AllowedKeys` as a property in `SecretsManagerConfigurationProviderOptions` and if it's not empty just get only those keys instead of enumerating all of them.

Would you accept such a PR? Or, probably, you have better idea how to implement this feature?

**Comment by Kralizek** [comment] 2020-04-05 08:23
Hi @aensidhe 
Thank you for opening this feature request.

I'm a bit thorn about whether or not this use case is actually within the scope of this library.

From one side I'd say "of course, it helps configuring", but on the other side the basic idea was to have a simple API.

It would be cool if you could share how you imagine this feature to be used. Would you mind adding a code snippet of what you have in mind?

That would make evaluating your request easier.

**Comment by aensidhe** [comment] 2020-04-05 12:14
First of all, it's totally fine to keep easy to use API, I admire that approach.

Answering your question:

Now I use your library like this:
```csharp
.ConfigureAppConfiguration((context, builder) => builder
    .SetBasePath(context.HostingEnvironment.ContentRootPath)
    .AddYamlFile("appsettings.yaml", false, true)
    .AddYamlFile($"appsettings.{context.HostingEnvironment.EnvironmentName}.yaml", true, true)
    .AddSecretsManager(configurator: options =>
    {
        var key = Environment.GetEnvironmentVariable("ENV_VAR_NAME");
        options.SecretFilter = x => x.Name.StartsWith(key);
        options.KeyGenerator = (entry, s) => s.Remove(0, key.Length + 1);
    })
```

And outside of my machine it doesn't work, since this requires an ability to enumerate secrets in whole account.

I'd like to use it like this:

```csharp
.ConfigureAppConfiguration((context, builder) => builder
    .SetBasePath(context.HostingEnvironment.ContentRootPath)
    .AddYamlFile("appsettings.yaml", false, true)
    .AddYamlFile($"appsettings.{context.HostingEnvironment.EnvironmentName}.yaml", true, true)
    .AddSecretsManager(configurator: options =>
    {
        options.AllowedKeys = { Environment.GetEnvironmentVariable("ENV_VAR_NAME") };
        options.KeyGenerator = (entry, s) => s.Remove(0, key.Length + 1);
    })
```

or

```csharp
.ConfigureAppConfiguration((context, builder) => builder
    .SetBasePath(context.HostingEnvironment.ContentRootPath)
    .AddYamlFile("appsettings.yaml", false, true)
    .AddYamlFile($"appsettings.{context.HostingEnvironment.EnvironmentName}.yaml", true, true)
    .AddSecretsManagerKey(Environment.GetEnvironmentVariable("ENV_VAR_NAME"), configurator: options =>
    {
        options.KeyGenerator = (entry, s) => s.Remove(0, key.Length + 1);
    })
```

Probably you're right and that should separate library.

**Comment by Kralizek** [comment] 2020-04-05 12:39
Have you thought about playing with the secrets visible to the IAM role used by the application?

The library would only enumerate through the keys visible to your application.

**Comment by jacobkiers** [comment] 2020-04-10 15:45
I would like this feature as well, since I have no control over the access rights and IAM policies for these secrets.

**Comment by aensidhe** [comment] 2020-04-10 21:06
@Kralizek thanks, but I'm not sure I have that control in current company. I'll see what I can do, thanks. In the meantime, issue can be closed, unless somebody else thinks it's worth the hurdle.

**Comment by alexisatkinson** [comment] 2020-08-04 14:21
> Have you thought about playing with the secrets visible to the IAM role used by the application?
> 
> The library would only enumerate through the keys visible to your application.

I had a similar requirement.  In terms of permissions, the extension requires kms:Decrypt, kms:Encrypto, secretsmanager:ListSecrets and secretsmanager:GetSecretValue.

If anyone is in a similar boat and can alter the IAM Policy attached to the role/user/group then something like the following works:

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Action": [
                "kms:Decrypt",
                "kms:Encrypt",
                "secretsmanager:ListSecrets"
            ],
            "Resource": "*"
        },
        {
            "Sid": "",
            "Effect": "Allow",
            "Action": "secretsmanager:GetSecretValue",
            "Resource": "list urn for the secret you want to allow here"
        }
    ]
}

You can't specify individual Urns for ListSecrets, but can for GetSecretValue and so it's possible to restrict access in this way.  Then, depending on the environment, you can specify the urn's to be allowed for that environment and then use the SecretFilter functionality so that GetSecretValue is only called on the whitelisted urn's e.g:

                        var accepted_urns = GetAcceptedUrns(hostingContext.HostingEnvironment.EnvironmentName);
                        config.AddSecretsManager(configurator: options =>
                        {
                            options.SecretFilter = entry => accepted_urns.Contains(entry.ARN);
                       }

This approach does mean that the application sees the urn of all secret keys with the LIstSecrets functionality, but is only able to retreive the secret keys that relate to the environment the user has access to.

**Comment by diegofrata** [comment] 2020-09-17 10:51
I think it's a fair use case to skip the listing of secrets if the aliases or ARNs are known in advance.

**Comment by alex-bolenok-centralreach** [comment] 2020-10-09 17:44
> Have you thought about playing with the secrets visible to the IAM role used by the application?
> 
> The library would only enumerate through the keys visible to your application.

The way I understand it, `ListSecrets` is an all or nothing deal: you either have the permission to do that or you don't.

Is there a way to limit the output from `ListSecrets` using IAM policies I'm not aware of?

`ListSecrets` accepts [filters](https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_ListSecrets.html), can we may expose them as a configuration option?

**Comment by yzfurkan** [comment] 2020-11-03 09:55
> ```cs
>         options.KeyGenerator = (entry, s) => s.Remove(0, key.Length + 1);
> ```

I can not use your second code: 
`options.AllowedKeys = { Environment.GetEnvironmentVariable("ENV_VAR_NAME") };
`
It gives me the error below:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'SecretsManagerConfigurationProviderOptions' does not contain a definition for 'AllowedKeys' and no accessible extension method 'AllowedKeys' accepting a first argument of type 'SecretsManagerConfigurationProviderOptions' could be found (are you missing a using directive or an assembly reference?)

```

**Comment by yzfurkan** [comment] 2020-11-03 09:56
> ```cs
> GetEnvironmentVariable
> ```



> First of all, it's totally fine to keep easy to use API, I admire that approach.
> 
> Answering your question:
> 
> Now I use your library like this:
> 
> ```cs
> .ConfigureAppConfiguration((context, builder) => builder
>     .SetBasePath(context.HostingEnvironment.ContentRootPath)
>     .AddYamlFile("appsettings.yaml", false, true)
>     .AddYamlFile($"appsettings.{context.HostingEnvironment.EnvironmentName}.yaml", true, true)
>     .AddSecretsManager(configurator: options =>
>     {
>         var key = Environment.GetEnvironmentVariable("ENV_VAR_NAME");
>         options.SecretFilter = x => x.Name.StartsWith(key);
>         options.KeyGenerator = (entry, s) => s.Remove(0, key.Length + 1);
>     })
> ```
> 
> And outside of my machine it doesn't work, since this requires an ability to enumerate secrets in whole account.
> 
> I'd like to use it like this:
> 
> ```cs
> .ConfigureAppConfiguration((context, builder) => builder
>     .SetBasePath(context.HostingEnvironment.ContentRootPath)
>     .AddYamlFile("appsettings.yaml", false, true)
>     .AddYamlFile($"appsettings.{context.HostingEnvironment.EnvironmentName}.yaml", true, true)
>     .AddSecretsManager(configurator: options =>
>     {
>         options.AllowedKeys = { Environment.GetEnvironmentVariable("ENV_VAR_NAME") };
>         options.KeyGenerator = (entry, s) => s.Remove(0, key.Length + 1);
>     })
> ```
> 
> or
> 
> ```cs
> .ConfigureAppConfiguration((context, builder) => builder
>     .SetBasePath(context.HostingEnvironment.ContentRootPath)
>     .AddYamlFile("appsettings.yaml", false, true)
>     .AddYamlFile($"appsettings.{context.HostingEnvironment.EnvironmentName}.yaml", true, true)
>     .AddSecretsManagerKey(Environment.GetEnvironmentVariable("ENV_VAR_NAME"), configurator: options =>
>     {
>         options.KeyGenerator = (entry, s) => s.Remove(0, key.Length + 1);
>     })
> ```
> 
> Probably you're right and that should separate library.


I can not use your second code @aensidhe : 
`options.AllowedKeys = { Environment.GetEnvironmentVariable("ENV_VAR_NAME") };
`
It gives me the error below:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'SecretsManagerConfigurationProviderOptions' does not contain a definition for 'AllowedKeys' and no accessible extension method 'AllowedKeys' accepting a first argument of type 'SecretsManagerConfigurationProviderOptions' could be found (are you missing a using directive or an assembly reference?)
```

**Comment by cjames9001** [comment] 2020-11-24 14:46
I would also like to see this feature as well, best practice security is to only give the minimum access necessary to perform the required action. Listing every secret first isn't necessary when you know exactly what secrets you are interested in in the first place.

**Comment by julealgon** [comment] 2020-11-26 20:05
Interesting that so many people want this like I do. Started using the library recently and immediately hit this problem: the role assigned to the lambdas do not have the `ListSecrets` permission, and this is how other applications in our stack work as well.

Wouldn't it be possible to just rely on the current `SecretFilter` property to perform this? Instead of making it just a simple predicate func, make it so that it is possible to include specific ARNs in the list of values. If the filter is provided, instead of "getting all the secrets" and "filtering them in-memory", one could just fetch just those secrets provided in the filter without calling `ListSecretsAsync`.

One idea that comes to mind is an API similar to assembly scanning done in [Scrutor](https://github.com/khellang/Scrutor#examples). It allows you to filter types for IoC registration, but it only filters on top of the ones you provide.

This doesn't hurt the API's public surface while giving the option for those who need more strict permissions.

@Kralizek , please reconsider this one otherwise this quirk might become a roadblock for us.

**Comment by Kralizek** [comment] 2020-11-26 20:34
So, I was looking at this issue together with @kipters who volunteered to solve it.

The problem is that it would require a major rework of the internals of this library, hence why I haven't worked on it sooner.

**Comment by julealgon** [comment] 2020-11-27 13:10
Thanks for the update @Kralizek . As I mentioned, there is a high chance that we'll have to abandon the library soon when going to production, as we anticipate not being able to provide the `ListSecrets` permission to our roles at this time.

If at all possible, do let us know about any ETA for this one if there is a plan to support it in the future.

**Comment by Kralizek** [comment] 2020-11-27 16:56
I don't have an ETA to be frank. I am between jobs right now so you can understand it's hard for me to find the time for this.

As for every open source project, contributions from the user base are always welcome, even if just to create a PoC.

**Closed** 2021-04-08 10:42 UTC
Labels: enhancement
